/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stream_media_demo_jni_JniTest */

#ifndef _Included_com_stream_media_demo_jni_JniTest
#define _Included_com_stream_media_demo_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stream_media_demo_jni_JniTest
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stream_media_demo_jni_JniTest_start
  (JNIEnv *, jobject);

/*
 * Class:     com_stream_media_demo_jni_JniTest
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stream_media_demo_jni_JniTest_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
